// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoULkEpu47XvWH2SLIc0FfdAxJj4dp2RA',
    appId: '1:219924415709:web:c6a7a83deca88b536ec734',
    messagingSenderId: '219924415709',
    projectId: 'dungeon-hero-maker',
    authDomain: 'dungeon-hero-maker.firebaseapp.com',
    storageBucket: 'dungeon-hero-maker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDhmscsZkirHhM2Lx6YQQ3afUmrSf289Q',
    appId: '1:219924415709:android:92df3d7aea9fdf616ec734',
    messagingSenderId: '219924415709',
    projectId: 'dungeon-hero-maker',
    storageBucket: 'dungeon-hero-maker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8G8sTy84DK5CKfro-QAIJ2AWjLbf34uc',
    appId: '1:219924415709:ios:60e29cc6aedf7c106ec734',
    messagingSenderId: '219924415709',
    projectId: 'dungeon-hero-maker',
    storageBucket: 'dungeon-hero-maker.appspot.com',
    iosBundleId: 'com.bjp.dhmv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8G8sTy84DK5CKfro-QAIJ2AWjLbf34uc',
    appId: '1:219924415709:ios:38968fd8d0266b856ec734',
    messagingSenderId: '219924415709',
    projectId: 'dungeon-hero-maker',
    storageBucket: 'dungeon-hero-maker.appspot.com',
    iosBundleId: 'com.bjp.dhmv1.RunnerTests',
  );
}
